import test from 'node:test';
import assert from 'node:assert/strict';
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { CHECKS, parseArgs, readHistory, runVerification, sourceFingerprint } from '../verify.mjs';
import { checkDocumentation } from '../check-docs.mjs';

const PREFIX = join(tmpdir(), 'resuelvelo-tooling-');
const SCRIPT = resolve(dirname(fileURLToPath(import.meta.url)), '../verify.mjs');

function fixture(t) {
  const root = mkdtempSync(PREFIX);
  t.after(() => {
    // This path is generated by mkdtemp; never remove a workspace or a parent.
    assert.ok(resolve(root).startsWith(resolve(PREFIX)));
    rmSync(root, { recursive: true, force: true });
  });
  mkdirSync(join(root, 'app'), { recursive: true });
  writeFileSync(join(root, 'app/page.ts'), 'export const value = 1;');
  writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'verification-fixture', version: '1.0.0', scripts: {} }));
  return root;
}

function run(root, options = {}) {
  return runVerification({ root, runCommand: () => ({ status: 0, stdout: 'fixture PASS\n' }), report: () => {}, ...options });
}

test('full checks run in order; subsequent runs append history instead of reusing passes', (t) => {
  const root = fixture(t);
  const calls = [];
  const options = { runCommand: (check) => { calls.push(check.name); return { status: 0, stdout: 'ok' }; } };
  const first = run(root, options);
  const second = run(root, options);
  assert.equal(first.status, 'PASS');
  assert.equal(first.full, true);
  assert.deepEqual(calls, [...CHECKS, ...CHECKS].map((check) => check.name));
  assert.equal(readHistory(root).length, 2);
  assert.notEqual(first.id, second.id);
  assert.equal(first.source.fingerprint, second.source.fingerprint);
  assert.ok(first.checks.every((check) => check.status === 'PASS' && existsSync(join(root, check.log))));
  assert.equal(existsSync(join(root, 'docs/history/verify.lock')), false);
});

test('failure preserves the exit code and skips later gates without calling them', (t) => {
  const root = fixture(t);
  const calls = [];
  const record = run(root, { runCommand: (check) => { calls.push(check.name); return { status: check.name === 'lint' ? 7 : 0, stderr: 'fixture output' }; } });
  assert.equal(record.status, 'FAIL');
  assert.deepEqual(calls, ['docs', 'tooling', 'test', 'lint']);
  assert.equal(record.checks[3].exitCode, 7);
  assert.deepEqual(record.checks.slice(4).map((check) => [check.status, check.reason]), [['SKIPPED', 'previous_failure'], ['SKIPPED', 'previous_failure']]);
  assert.equal(readHistory(root)[0].status, 'FAIL');
});

test('a selected pass stays partial and unselected controls are explicitly skipped', (t) => {
  const record = run(fixture(t), { selected: ['test'] });
  assert.equal(record.status, 'PASS');
  assert.equal(record.full, false);
  assert.deepEqual(record.selected, ['test']);
  assert.equal(record.checks.filter((check) => check.status === 'PASS').length, 1);
  assert.ok(record.checks.filter((check) => check.status === 'SKIPPED').every((check) => check.reason === 'not_selected'));
});

test('spawn errors and timeouts are recorded as failures, and the lock is released', (t) => {
  const root = fixture(t);
  const error = Object.assign(new Error('fixture timeout'), { code: 'ETIMEDOUT' });
  const record = run(root, { selected: ['test'], runCommand: () => { throw error; } });
  assert.equal(record.status, 'FAIL');
  const check = record.checks.find((item) => item.name === 'test');
  assert.equal(check.exitCode, null);
  assert.equal(check.error, 'ETIMEDOUT');
  assert.equal(existsSync(join(root, 'docs/history/verify.lock')), false);
});

test('editing the same input during passing checks invalidates their result', (t) => {
  const root = fixture(t);
  const record = run(root, { selected: ['test'], runCommand: () => { writeFileSync(join(root, 'app/page.ts'), 'export const value = 2;'); return { status: 0 }; } });
  assert.equal(record.checks.find((check) => check.name === 'test').status, 'PASS');
  assert.equal(record.status, 'INVALIDATED');
  assert.notEqual(record.source.fingerprint, record.sourceAfter.fingerprint);
  assert.equal(record.reason, 'inputs_changed');
});

test('history and secret configuration do not enter the source fingerprint or summary', (t) => {
  const root = fixture(t);
  const before = sourceFingerprint(root);
  writeFileSync(join(root, '.env.local'), 'FIXTURE_SECRET=never-record-this-value');
  const record = run(root, { selected: ['test'] });
  assert.equal(sourceFingerprint(root), before);
  assert.ok(!JSON.stringify(record).includes('never-record-this-value'));
});

test('a new source folder covered by TypeScript wildcards invalidates a passing run', (t) => {
  const root = fixture(t);
  const record = run(root, { selected: ['test'], runCommand: () => {
    mkdirSync(join(root, 'another-checkout'));
    writeFileSync(join(root, 'another-checkout/page.tsx'), 'export const added = true;');
    return { status: 0 };
  } });
  assert.equal(record.status, 'INVALIDATED');
  assert.notEqual(record.source.fingerprint, record.sourceAfter.fingerprint);
});

test('an existing lock blocks another invocation without running commands or taking its lock', (t) => {
  const root = fixture(t);
  mkdirSync(join(root, 'docs/history'), { recursive: true });
  const lock = join(root, 'docs/history/verify.lock');
  writeFileSync(lock, 'foreign-lock');
  assert.throws(() => run(root, { runCommand: () => assert.fail('must not run') }), /Otro ejecutor/);
  assert.equal(readFileSync(lock, 'utf8'), 'foreign-lock');
  assert.equal(existsSync(join(root, 'docs/history/verification.jsonl')), false);
});

test('arguments reject unknown, duplicate, missing or mixed controls and preserve canonical order', () => {
  assert.deepEqual(parseArgs(['--only', 'build,test']).selected, ['test', 'build']);
  assert.ok(!parseArgs(['--quick']).selected.includes('build'));
  assert.equal(parseArgs(['--history']).mode, 'history');
  for (const args of [['--only'], ['--only', ''], ['--only', 'unknown'], ['--only', 'test,test'], ['--quick', '--history']]) assert.throws(() => parseArgs(args));
});

test('the CLI returns nonzero and records an actual failing subprocess', (t) => {
  const root = fixture(t);
  mkdirSync(join(root, 'scripts'));
  copyFileSync(SCRIPT, join(root, 'scripts/verify.mjs'));
  writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'verification-fixture', scripts: { 'docs:check': 'node -e "process.exit(7)"' } }));
  const result = spawnSync(process.execPath, [join(root, 'scripts/verify.mjs'), '--only', 'docs'], { encoding: 'utf8', windowsHide: true, timeout: 15000 });
  assert.equal(result.status, 1, result.stderr);
  const [record] = readHistory(root);
  assert.equal(record.status, 'FAIL');
  assert.equal(record.checks[0].exitCode, 7);
});

test('history reader returns only the requested tail across byte chunk boundaries', (t) => {
  const root = fixture(t);
  mkdirSync(join(root, 'docs/history'), { recursive: true });
  const records = Array.from({ length: 200 }, (_, id) => ({ id, note: 'á'.repeat(100) }));
  writeFileSync(join(root, 'docs/history/verification.jsonl'), records.map((row) => JSON.stringify(row)).join('\n') + '\n');
  assert.deepEqual(readHistory(root, 5).map((row) => row.id), [195, 196, 197, 198, 199]);
});

function documentationFixture(t) {
  const root = fixture(t);
  mkdirSync(join(root, '.cursor/rules'), { recursive: true });
  mkdirSync(join(root, 'docs/index'), { recursive: true });
  writeFileSync(join(root, 'AGENTS.md'), '# Project\n[Index](docs/index/MASTER_INDEX.md)\n');
  writeFileSync(join(root, 'CLAUDE.md'), '@AGENTS.md\n');
  for (const name of ['project-engineering', 'orchestration']) writeFileSync(join(root, `.cursor/rules/${name}.mdc`), '[AGENTS](../../AGENTS.md)\n');
  writeFileSync(join(root, 'docs/guide.md'), '# Guide\n');
  writeFileSync(join(root, 'docs/index/MASTER_INDEX.md'), '# Index\n[Guide](../guide.md)\n');
  return root;
}

test('documentation coverage detects a new unindexed document and a dangling index link', (t) => {
  const root = documentationFixture(t);
  assert.deepEqual(checkDocumentation(root).errors, []);
  writeFileSync(join(root, 'docs/new.md'), '# New\n');
  assert.ok(checkDocumentation(root).errors.some((error) => error.includes('Sin indexar:')));
  writeFileSync(join(root, 'docs/index/MASTER_INDEX.md'), '[Missing](../missing.md)\n');
  assert.ok(checkDocumentation(root).errors.some((error) => error.includes('falta ../missing.md')));
});

test('documentation rejects oversized always-loaded entries and a missing Claude import', (t) => {
  const root = documentationFixture(t);
  writeFileSync(join(root, 'AGENTS.md'), '[Index](docs/index/MASTER_INDEX.md)\n' + 'x'.repeat(8001));
  writeFileSync(join(root, 'CLAUDE.md'), '# Standalone rules\n');
  const errors = checkDocumentation(root).errors;
  assert.ok(errors.some((error) => error.includes('supera el presupuesto')));
  assert.ok(errors.some((error) => error.includes('debe importar')));
});
